#ifndef LIVROS_H_INCLUDED
#define LIVROS_H_INCLUDED

lusiadas()
{
    printf(R"EOF(MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMWWWNNNNXXXXXXXXXXXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOdlc::;;,;;,,,,,,,,,::;:clododddddxxxxxxxxxxxxxxkkkkkkkkOOOOOOOOOOOOOOO00000000000000KKKKKKKKKKKKKKKKKKKXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc..      ...........'..'..,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'',,,'',,,,',,,,,,,,,,,,,''''',,,,,,,,,,,,,oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:..       ..........'''''',,,,,,,,,,,,,',,,,,,,,,,,,',,,,,''',,'''''''''''''''''''''''......................cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:..         ........','''',,,,,,,,,,,,,,,,,,,,,,,,''''',,,,,,,,'''''''''''''''''''''''......................:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:..        .........,'''''',,,,,,,,,,,,,,,,,,''',''''',,,,,,,,''''''''''''.'''''''''''......................:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc..         ........''',,',,,,,,,,,,,,,,,,,,,,'''''''',,,,,,,''''''''''''...''''''..........................;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc..          .......''''',,,,,,,,,,,,,,,,,,,,'''''''''',,,','''''''''''''..''''''...........................;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc..         ........'''',,,,,,,,,,,,,,,,,,,,,,,,,'''''',,,,,'''''''''''''''..'''............................;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc..        .........''',,,,,,,,,,,::c:;,,,,,,,,,'''',:cc::,''''''''''''''''.','.............................;0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc..         ........''',,,,,,,;lddxOKX0d:,,,,,,,'',';kNKOo,'''''''''''''''.'cl,.'...........................;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl..         ........'''''',,,cONOc;;lOWWk;;::::,,'',;kMKkl,,',::,';lc,;ccc:;ol,.,cl,..:dlcol,..,lc'.';;,;'..,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl.......     . .....'',''',,;kWXo,,,,lXM0ldkoldc,'',,kWKkl,,':0O;'cKOcOk:c::0O;.:kKo'.oXo':0k,':xx;.,c;''...,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl.......       .....',,''',,:0MXo,,,,c0W0d0Xd:;,,'',,xWXkl',':0O:'cKOckXko:;OO,,ld0O;.lKl.'x0:;ccxl'.,::,'..,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl'..   .    .    ...'''''',,:OWNx;,,,c0Wk:lkKKOl,''',xWXOl,,;l00:'c0O;;ld00lkO;cd:dKd'lKo.,xd,cc'ld;''.'c,..,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl'..   .         ...'''''',,,dNMXo;,,oKO:;:;;dXk;',',xWXOo:lxoOXxloKOclc;dklO0ldl.,xOcl0xccc,;c,.,l:;;,;;...,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo'..  ...        ...''''''',,;o0NX0kxxo;,:ddldxc',,,;oOkxdoxd::dxo:ll;clc:,,::;:,'',;,,;;;'..''.............,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo'.......       ....'''..',,,,,;cllc;,,,,,;::;,'',,,,,,,,'',',''''''''''..'''''''''''..'....................'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo'.. ..         .....''..',,,,,,',,,,',,,,,',,,'''''',,,''''',''''..''..''''''''''''.''.....................'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo'..           ......''..'',''''',,'''',,,,',,'''''''','''''''''''''''''..'''''''''.........................'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd'..          .......''...'''''''''''',,,,,,'''''''',,'''''''..'''..'',;:;'.'''',;,,,,'.....................'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd'..           .. ...''...''''''''''''''''''''''''';oc,,,;;:c;',::c:,.co;,:c:cclcloc:lc'....................'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd'..              ...''...''''',,'''''''''''''''''';xo:llodool,;olll;':ol:;:::::::;;;;;'....................'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd'.               ...''...',,,,,,,''''''''''''''''''cl::c:;;;;'';,',''''''..................................'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'.         ..    ...''...'',,,,,,''''''''''''''''''''''..''''''''..''''....................................'xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd'..         . ..  .......'''''''''''''''''''''''''''''..''.''.''.''.........................................xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd,'......       ..........''''''''''''''''''..'''''''..'''''''''..'''...........''...........................xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,'......         ........''''''''''''''''.''''''''''''''''''''''''''...''...................................xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,..              .........''''''''''''''''''''''''''''..'''''''''''....''...................................xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,..              .........''''''''''''''''''''''''''........''''.'''...''...................................xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,....            .........'''..'''''''''''''''''..................'''''.....................................xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,'...            .........''..'''''''''''''.''''''.......''''.......''......................................xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,..             ..........'''''''''''''''''..''''''....'''''..''............................................xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk;.....            ........'''''''''''''''''''''''.'...''....................................................xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,'....            ........''''''''''''''..'''''''''.......'''......'........................................xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;.. .             ........'''.'''''''''...'''''''''''....'''................................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;...              ........''''.......''....'''......''''''..................................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;'....            ........''''...............''......'''''.....''...........................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;'.. .            .........'''...''.....''............'''''.................................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;''..            ..........''..........''''...................'.............................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;'......          .....................''''..................'..............................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:'..  ..        . ..............'''...''''..................................................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:....          .. ...............'''..''''..................................................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;.....        ...................'''..................'''...'''.............................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:;;...         .....................................''......'''.............................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:'.. .    .       ..............'...........................'...............................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:;;'..            ................'''.......................................................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0c;,....           .............''''...................'''...................................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc'. ... .         .............''''..................''.....................................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc,,''..      ... ..............'''''........................................................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc',,,.    .   ....................''........................................................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl,'.. ..   ...   .......................................'...................................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl''.....     ..   .........................................''...............................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl,,;c;.     ...   ......................'..................''...............................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl;c;'....   ...........................................''...................................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl,'......     ..  ..........................................................................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo,',:.... .   .. ...........................................................................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo',:;'... ..  .  ...............................'...........'''.............................................dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo;c:.'...... ..............................................'''''''..........................................xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo,'...........................................'..........''..'''............................................xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo'.....  ...........................................................'.......................................xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,..... ....................................................................................................xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,....... ..................................................................................................xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,.......  ...................................................................''............................xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,...................................'......................................................................xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,..........................................................................................................xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,..........................................................................................................xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,.................................................................................'........................xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,..........................................................................................................xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,..........................................................................................................xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,..........................................................................................................xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,.................................'........................................................................xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMMMMMMMMWk,........................................................................'''...............................xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMMMMMMWk,............................................................'',:l:,clcccldo;..............................xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWk;'.........................................................:x0OONMkcooooc:cc;:;............................xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk;'.........................................................lNWXKWWx:lcldooododc............................xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWWWWNNWWWWWWWWWWWWWWWWWWOll;'.......................................................lXKddK0c;oool:;;,''.............................xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WWWWWWWWWWWWWWWWWWWWWWNNWWWNNNNNNWWWWWWWWWWWWOdxddxdc....................................................,xo..;l;.,'.................................';:o0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MWWWWWWWWWWWWWWWWWWWWNXKKXNNNNNNNNNWWWWWWWWWW0dxdxO0k,....................................................''..................................,:lodk0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMWWWWWWWWWWWWWWNOdxkO0XNWWWNNNWWWWWWWW0dxdd00k,................................................................................,:codkOKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWWMMWWWW0kxdddxO0XNNNWWWNWWWWWKdc;cxOk;........................................................................,;cldxO0XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWNXK00OkkkO0KXNNWWWWWWKo,.,:;,.................................................................,;cldxO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNK0OkkOO0KNWWWXl'..,;'.........................................................,;cloxO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXKOkkkkO0KOc'......................................................,;:loxk0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKK0Okxo:'.............................................,;:loxOO0KXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNX0o,....................................',;cldxO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd;...........................',:cldkO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdl:,'.............';:lodkOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0OkxdollcloxOKXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM)EOF");
}

maias()
{
    printf(R"EOF(MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxolldkO00XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxl;'...':::;;coxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx:'',,,'.,::c:,;;,,;coxkKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl;;:::c;'.,::c:,;;,,,,,,,;coxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkcccc;,,'..,:cc:;;;,,;;;;;;;;,,;coxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdc:;;;;,,'.,:cc:;;;;;,;;;;;;;;,,;;;;:coxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl;::;;,....'::::;:;;:lllc:;;,,;;;;;;;;;;;:codxOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl;;,.......'c:;;;:;;clcllllllcc;;;;;;;;;;;;;;;;:ldxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl,,'.......'c::;;:;,cl:ol:cllodolllc::;;;;;;;;;;;;;;:coxOXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl','.......':::;;:;;cl:cooxkdool::clloolll:;;;;;;;;;;;;;;:ldx0XNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc',,'......':::;;:;;lccl;;llccllccccccclloooooolc:;;;;;;;;;;;;:ldk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc,:;'......':::;;:;;lccl:;;;;;;;;;:ccllllccccclllllolc:;;;;;;;;;;;:cldk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc,;,'......':::;,:;;cccl:;;;;;;;;;;:;;;;:ccccccccccllllllllc:;;;;:;;;;;:cldk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc':;'......':::;,:;;lccl:;;;;;;;;::;;;;;:;;;;;;:ccccccccllllllllcc::::;;:::::codONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc';,''''...':::;,::;lccl:;;;;;;;;;:;;;;;:;;;;;;;;;;;;::clllccllllllllcc::::::::;lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl';;;::,...':::;,::;llcl:;;;;;;;;;;;;;;;;;;;;;;;;::;;;;;;;::cllcccclllllllllc:::lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl;::;,'....':::;,:::llll:;:::;;;;;;::;:::::;;::;;:::;;;;;;::::::::cccclooooool::lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl,;''......':::,,::;llll:;::::::::::cllc:;;::::::::::;;;;;;;;:::::::::cldoolll::lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl',''......';::,,::;lllo:;;:::::::::oxoddllcc::::::::;;:::::::::::::::::::ccll::oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl',,,;;;;,',::c,,:::lllo::::::::::::clodxxxkdooolclol:::::::::::::::::::::clol::oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl;::;;;,''.':::;,:::lllo::::::::::::::::cclooooddlddodoolllc::::::::::::::clol::oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo;:;,,;;;;',:::,,:::lllo:;::::::::::::::::::::::::clllodxxxdooolccc:::::::clol::oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo;cc::;;,'.':::,,:::ollo:::::::::::::::::::::::::::cc::::ccclooooddl::::::clol::oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo;:;;,,;;,',:::;,:::lllo::::::::::clcc:::::::::::::oxddl::::::::cclc::::::cool::dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo;::;;,,'..':::;,:::llloc:::::::::lOkollcc:::::::::clooc::::::::::::::::::cool::dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo,;'.....  .:::,,:::llloc:::::::::lOkoxxlodc::oollc::clc::::::::::::::::::clooc:dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl';;,....  .:::;,:::lllo::::::::::cdooddoxko:cxkxkdcdxddolllcc::::::::::::coolc:dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl,:,....''.'::c;,:::llloc::::::::::::::llcll:cooodocoxdxkddxdddoooolc:::::loolc:dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl,::;;:;;;',:::;,:::llloc::::::::::::::::cc::::::::::lxdollooodxxdxxo:::c:loolccdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo;:;''.....'::c;,:c:llloc::::::::::::::::::c::::::::::clc::::cccclclc:::::lodoccxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo',,''.....'::c;,:::olloccccccccc:::::c:::::::::c:::::::::::::::::::::::cclodoccxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo',;''.....'::c;,:c:ooloccccccccc:::::::::::::::c:::::::::::::::::::::::c:lodo:cxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo',,'......':::;,:c:ooloc:ccccccc:::::::cc::::cccc:ccc::::::::::::::::::c:lodoccxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo';:,......':::;,cc:ooloc:ccccc:::::c:::::::::ccccc:::::::::::::cccc::::::lool:cxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo';;,'.....'::c;,cc:ooloc:ccccc:::ccc:::::::::ccc::::c:::::::::ccccc::::::cool:cxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo';;'......'::c;,:c:ooloc:cccccc::cccccc:::::cccc::::cc:::::::::::::::::::lool:cxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo';,'......,:cc;,:c:loloc:cccccccccccccc::::::cccc::::c:::::::::::c:::::::loolccxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo';;'......'::c;,:c:loloc:ccccc:ccccccc:::ccccccccccc:cc::c:::::::::::::::coolcckWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo',;'......'::c;,:c:loloc:cc:ccccccccccc:::::ccc:oddxdddl::::::::::cc:::::loolcckWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo';:,......':::;':c:loloc:::::ccccccccccc:::::cccclodollc::::::::::cc:::::lool:ckWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo';:,......':::;,:c:loloc::::::::::cccccc::::ccc::::::::::::::::::::::::::clol:ckWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo';:,......':::;,:c:ooloc::::::::::ccc:ccc::::c:::::::::::::::::::::::::::llol:ckWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo';:,......':::;,:c:loloc:::c::::::c:::::::::::::cc:::::::::::::c:::::::::clol:cxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo';c,......'::c;,:::llloc::::::::::::::::::::::::c:::c::::::::::::::::::::clol:cxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo':c,......'::c;,;::llloc:::::::::::::::::::::::::::::::::::::::::::::::::clolccxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo';;'......';::;,:::llclc:::::::::::::::::::::::::::::::::::::::::::::::::clooccxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd';:,......';::;,;::llloc:::::::::::::::::::::::::::::::::::::::::::::::::clol::xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd';:,......';;:;,;::llloc:::::::::::::::::::::::::::::::::::::::::::::::::clll::xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd';:,......';;:,';::llloc:::::::::::::::::::::::::::::::::::::::::::::::::cclc::xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd',;'.......;;:;,:::llllc:::::::::::::::::locoocc:cdoooccllcccc:;;;;:::::::clc::dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd',,'.......;;:;,::;clllc::::::::::::::::cxo,lxxdc:dxxddxddxxdo:;;;::::::::clc::dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd',,''.....';;:;,;:;clll::::::::::::::::::locllloc:llllllcclcc:;;;;::::::::clc:;dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd',,''.....';;;,';:;clcl:::::;;;::::::::::::::::::::;::;;;;;::;;;::;;;;::::clc:;dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd',,''.....';;;,';:;clcl::::::;;:::::::::;;:::::coollol:cc:;;;;;:::;;;;;;;:ccc;;dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd',,''.....';;:,,;:;clcl:;:;:::::::::::;;::::::::llloll:cc;;;;;::::::;;;;;:ccc;;oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd',,''.....';;:;,::;clcc:;;;::;;;;;;;;::;;;:::::::::;;;;;;;;;;;;;;;;;;;;;;::cc;;oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd',,''.....';;:;,::;cccl:;;;;;;;;;::;;;:;;;;:::;;;;;;;;;;;;;;;;;;;;;;;;;;;:ccc;;oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd',,''.....';;:;,::;cccc:;;;;;;;;;;;;;;;;;::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:cc;;oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,,,''.....';;:,,::;cc:c;;;;;;;;;;;;;;;;;;;:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::;;oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,,,''.....';;:,,::;cccc:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::;;lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx,,,''.....';;;,,::;cccc:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::;;lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx,,,''.....';;;,,;:;cccc:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::;,lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx,,,''.....';;;,,;;;cc:c;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::;,cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx,,,''.....';;;,,;;;:::c;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:c:;,cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx,,,''.....';;;,,;;;c::c;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::;,cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx,,,''.....';;;,,;;;c::c;,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:c:;,cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx,,,'''....';;;,,;;;::::;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:c:;,cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,,,'''....';;;,,;;,::;:;;;;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:c:;,cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,,,'''....';,,,,;;,::;:;,,;,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::;,cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,,,'''....',,,,,;;,::;:;,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::;,cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,,,'''....',,,,,,,,::;:;,,;;,,,,,;;;;;;;,;;;;;,,;;;;;,,;;;;;;;;;;;;;;;;;;;:::;,c0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,,,'''....',,,'',;;::;:;,,,,,,,,,,;;;;,,;;;;;;,,;;;,,,,;;;;;::::;;;;;;;;;;;::;,c0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk,,,'''....';,,,',;,:;;:;,,,,,,,,,,;;;;;;;;;;;;,;,;,,;;;:ccccccc:;;;;;;;:cc:::;;c0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk;:;'''....',,,,',;,;:::;,,,,,,,,,,,;;,,,;;;;;;;:::::ccccc::;;;;;;;::;:::cccl:;,c0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk:ol;''....',,,,,,,,::;:,,,,,,,,,,,,,,,,;::;;:cclcc::;;;;;;;;::::::ccccc:::::;;,c0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk:loc''....',,,'',,,::;:,,,,,,,,,,,,;;;,;cc:;;;;;;;;,;;:::::::cllccccc:;;,,,;;;,cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk;loc,.....',,,,,,,,::;:;,,,,,,,,,,;;;;,,,,,,;;;;;::::::ccccccccc:;;;;;;;,,;;:clkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk;cl;''....',,,,,,,,;;;:;,,,,,,,,;;;;,,,,,;::ccc::ccccccccc:;;;;;;;;;;;;;:ldk0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO:cc:,'....',,,'',,,;;;:;,,,,,;;,,,;;::::::cccccccccc::;,,,;;;;;;;;:cldk0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;:ll:'....',,,,',,,;;;;,,;;::c::::::::ccccccccc:;;;;;;,,,,,;;:codk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;,;;;'....',,,,',,,;;,:::cclc:c::cccccc::;;,,,,,;;;;,,,,;cldk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO:;,'''....',,,,',,,;:,::::cclccccc:;,,,,,,,,,,,;;;;;cldk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO:::;'''...',,,,,,,,::::cccc::;;,,,,,,,,,,,,,,;:coxk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOc:::::;,'.',,,,,,,,;::::;;,,,,,,,,,,,,,;:coddkKXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0lcc;;;;;,'',,,,,,,,,,,,,;,;;;;;;,,;:coxOKXWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKo:cll:;,'.',,,,,,,,,;;;;;,,,;;:loxOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOc;;:::;,'',,,,,,,,;;,,;:cldk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o;''''..',,,'',,;:codk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0dc,...',,::coxOKXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKkxdxk0KNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM)EOF");
}

desassossego()
{
    printf(R"EOF(MMMMMMMMMMMMMMMMMMMNK0000000OOOOO0K000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000KKK000000000KKK0000000000000000kdddddlcooooooooooooooooooooooollollllllllllllllllllllllllllll
MMMMMMMMMMMMMMMMMMMWKK000000OOOO00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0000000000000kdddddocoooooooooooooooooooooooooooooollllllllllllllllllllllll
MMMMMMMMMMMMMMMMMMMWXKK00000000O00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0kdddddoloooooooooooooooooooooooooooooooollllllllllllllllllllll
MMMMMMMMMMMMMMMMMMMWXKK00000000O00KKKKKKKKKKKKKKKKKKKKKKKKXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0kdddddolododddddddooooooooooooooooooooooooooolllllllllllllllll
MMMMMMMMMMMMMMMMMMMWNKKK0000000000KKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0kdddddolodddddddddddooooooooooooooooooooooooooloolllllllllllll
MMMMMMMMMMMMMMMMMMMMNXKKKK0000000KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKXXXXXXXXXXXXXXKKXXXXXXKXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0kxddddoldddddddddddddooooooooooooooooooooooooooooolooollllllll
MMMMMMMMMMMMMMMMWKOkxxxddddxxxxxxxkkkkkkkkkOOOOOOOOOOOOO00000000KKKKKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKXXKKKXXXXXXXXXXKKKKKKKKKKKKKKKOxxxxdoodddxdddddddddddddddddddddddddddddoooooooooooooolllllll
MMMMMMMMMMMMMMMMO;''''''..,:cccccccccccccccccccclllllllllllloooooooooooddddddddxxxxxxxxxkkkkkkkxxxxxxxxxxxxxxxxxxxxxkkkkkkxxxxxxkkkkkkkkkxxxxxddddxxxxxdxxxdxxxdddddddddddddk0KXXKKkdoooooooooooooooolll
MMMMMMMMMMMMMMMMO;.''''''',:cccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllooooooooooooloooooolllllllllllllcld0XNXX0xooooooooooooooooool
MMMMMMMMMMMMMMMM0;...''...,:cccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllolooooooooooooooooooooollllllllllllllc:cd0XNKxooooooooooooooooooo
MMMMMMMMMMMMMMMMO;.'.''..',ccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllooooooooooooooolllllllllllllllllllllc::lx0Kxooooooooooooooooooo
MMMMMMMMMMMMMMMMO,...''..';cccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllloollolllllllllllllllllllllllllllccloxxddooooooooooooooooo
MMMMMMMMMMMMMMMNd'...''..';ccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllollllllllllllllllllllllllllllllllldddddddoooooooooooooo
MMMMMMMMMMMMMMMXl....''..';cccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllloooollllllllllllllllllllllllllllllllddddddddddooooooooooo
MMMMMMMMMMMMMMMXl....''..';cccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllollllllllllollllllllllllllllllllllldxdddddddddddddoooooo
MMMMMMMMMMMMMMMXc........';cccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllloolllllllllllllllllllllldxddddddddddddddooooo
MMMMMMMMMMMMMMMXl........';cccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllolllllllllllllllllllllllloddddddddddddddddddoo
MMMMMMMMMMMMMMMXl........';ccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllodddddddddddddddddddo
MMMMMMMMMMMMMMMXl........';ccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllodddddddddddddddddddd
MMMMMMMMMMMMMMMXl........':ccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllodxxxdddddddddddddddd
MMMMMMMMMMMMMMMXc........':ccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllodxxxxddddddddddddddd
MMMMMMMMMMMMMMMXc........':ccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllodxxxxdxddddddddddddd
MMMMMMMMMMMMMMMK:........':cccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllloooooolllllllllllllllllloxxxxxxxxxdxxxddddddd
MMMMMMMMMMMMMMMK:........':ccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllooollllllllllllllllllloxxxxxxxxxxxxxxdddddd
MMMMMMMMMMMMMMMK;........,:cccccccccccccccccccccccccccccclllllllllllllllllllllooooollllllllllllllllllllllllllllllllllllllllllolllllllllllllllllllllllllllollllllllllllllllllllllllloxxxxxxxxxxxxxxxxxxxd
MMMMMMMMMMMMMMM0;........,:ccccccccccccccccccccccccccccccllllllllllllllllllllldxdxolooollooollollolllllllooolloolllllolllllodoolllolllllllooolloooolooolllllllllllllllllllllllllllloxxxxxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMM0,........,:ccccccccccccccccccccccccccccccllccllllllllllllllllldxoxdlxxoloxxxoodxxdlodxdloxxxooxdddoddoxolllodxdoddoddloxdldxxdodxdoodxollllllllllollllllllllllllllloxxxxxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMMO,........,:cccccccccccccccccccccccccccccclccclllllllllllllllllodooolodolodddoloodolooodoodddoododdoddodolllooddoddoddooddooxxdodxdoodxdlllllllllllllllllllllllllllloxxxxxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMMO,........,:cccccccccccccccccccccccccccccclccllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllollllllllllllllllollollloollllllllllllllllllllllllllllloxxxxxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMMk'........,ccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllloxxxxxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMMk'........,ccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllloxkxxxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMMx'........,ccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllloxkxxxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMWx.........,cccccccccccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllldkxxxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMWd.........,cccccccccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllldkkkxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMWd.........,cccccccccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllldkkkkxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMNo.........;cccccccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllldkkkkxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMNl.........;ccccccccccccccccccccccccccccccccccccllllllllllllllllllllllodollllloooolloooollooolloooolllllloooolllllllllloooolllllllloooollllllllllloolllllllllllllllllldkkkxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMNl.........;cccccccccccccccccccccccccccccccccllllllllllllllllllllllllloOklllllokOolldO0xllddlldkxoxkolldxdooxxolllllllokkoodxdllldxdodxxollllllllllllllllllllllllllllodkkkxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMNl.........;cccccccccccccccccccccccccccccccccclllllllllllllllllllllllloOkllllllkOollok0OdodllloOkdkkoloOOolldOklllllllokkllokOdloOklllx0xlllllllllllllllllllllllllllloxkkkkxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMXc.........;cccccccccccccccccccccccccccccccccccllllllllllllllllllllllloOklloollkOolllodkOxlllloOkxOxlloOOolldOklllllllokkllokOoloOkollx0xllllllllllllllllllllllllllllldkkkkxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMXc.........;cccccccccccccccccccccccccccccccccccclllllllllllllllllllllloddoodolodxollllloxolllloxxodxdoloxdooddollllllloxxooddollldxdooxdlllllllllllllllllllllllllllllodkkkxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMX:.........;cccccccccccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllldxxxxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMK:.........;ccccccccccccccccccccccccccccccccccllcllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllldxxxxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMK;.........;cccccccccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllloolllllllllllllllllllllllllllllldxxxxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMK;.........;ccccccccccccccccccccccoxdloddlccloxdloollldoodollllodlllllododollooooolllloooooollllooddollloooolloodooollllloooooollloooooolllllllllllllllllllllllllllllldxxxxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMM0;.........;ccccccccccccccccccccccdkdccokklccdOdlollldOxoolllloxOdlllokkooollxkdoolloxOkoldkkoloxkdddlldkdodoloxOdodolloxdooddolodkdodxkdllllllllllllllllllllllllllllldxxxxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMM0,.........;ccccccccccccccccccccccdkocclkklccdOdoolclldxkkolloddkkollldkkkolloxkkdllx00xlllx0xlldkkkdllokkkdollxOxoollokOolooooloOkolldOkllllllllllllllllllllllllllllodxxxxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMO,........':ccccccccccccccccccccccdkdllddoccldkdloolloooxkoloddldOxllododOxlodookOolok0kolokOdlododOkoldookOdllxOdlooookOdloxkdlokOdlldOxllllllllllllllllllllllllllllldxxxxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMO,........':ccccccccccccccccccccccllllllccccllolllllllooollloolloddllodooolllddodolllodddoodolloddodollddoddllodxdooollodddoddolloddooddlllllllllllllllllllllllllllllldxxxxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMO'........':cccccccccccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllldxxxxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMO'........':cccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllldxxxxxxxxxxxxxxxxxxx
MMMMMMMMMMMMMMk'........':ccccccccccccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllooollolllllollolllllllllllllllllllllolcccloooddddx0Oxooo
MMMMMMMMMMMWKx:.........':cccccccccccccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllolllloollllllllllllllllllooooooollllllllolllllllllllllllllllllc:;::::::cccllllllc
MMMMMMMMMMMXl...........':cccccccccccccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllloooooooolllllllllllllllloooooooooollllloollllllllllllllllllllldkkdxkkkxdkO00OO0KKK
NXNMMWNXXWMNx:,.........':ccccccccccccccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllooolollloollllllloollloooooooooooooollooooollolllllllllllllllllldKXXXNXXXXXXXXXXXKK0
oldkkxolodxdll,.........':ccccccccccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllollllllllllllllllllllllllllloooooollllllloollllllllllllllllllllloxxkkkxdxkkxdddxxdll
kxdoldxkkxddkOc.........':cccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllloollllloollllllllllllllllllllooolllllllllooollllllllllllllllllllodxxxdoooxxdolodxdoo
NNNNXXXNNNNNNXo.........'cccccccccccccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllloollllloolllllllllllllllllllooolllllllllllollllllllllllllllllllooooodxxxkxdxkkkxdod
OOkkkO00OxxkOOc.........,ccccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllloooollollllllloolllllllllooollllllllllllllllolllllllllllllllllokOO0KNNK000KXX0OO0K
xxxxxxkkxxxxxx:.........,ccccccccccccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllooooooollolllllllllllolloollloooollllllllllllllllloollllllllllllloxxkkkkxdddxxxkkxxxx
oddxddddddddoo,.........,cccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllloooooolloollllllllllllllllllllllllllllllloollllloooolllllllllllllooloxkkk0KKKXXNNWNNK
KK0OkO0XXK0OOk:.........,cccccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllloolllllloollllllllllllllllllllllllllllllllllllllllllooooolllllllllllloxOKXNNWMMMMMMMWWWWW
000OkkkOOOOOOx;.........,ccccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllooolllllllllllllllllllllllllllllllllllllllloloolllllllllllldKMWMMMMWWWWWWWNXNNK
xxddddoooooloc'.........,cccccccccccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllloolloooollllllllllllllllllllllllllllllllllllllllllollllllllllllo0WWWWWNNNNXXXXKKK0k
NNX0kOkxdddddl'.........,cccccccccccccccccccccccccccccccccccllllclllllllllllllllllllllllllllllllllllllllllllllollllooooooooolllllllllllllllllllllllllllllloolllllllllollllllllllllllokOOOOO000Okkkkkxxxd
MMMMWNNXXXXKOkc',,,,,,,,;::::::::::::::::::::::ccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllooooooooolllllllllllllllllllllooooooollooolllllllloollllllllllllloollcclooolllcclollc
MMMMMMWWWMMMMXo:::cccccc:::::::::;;,,,;;;;;;::::::::::::::::::ccllllllllllllllllllllllllllllllllllllllllllllllloolooooooooooolllllllllllllllllloodddoodoolooooooolloooollllllllllllloddxkkdlclxkxdlc::co
WWNNWWMMMWWWWKo::::ccccc::::::::;,,,,,,,,,;;;:::::::::::::::::ccllllllllllllllllllllllllllllllllllllllllllllllllooooooooooolllllllllllllllllloooooooooooloooooooooooooooollllllllllloOWWWNXKKXNWWWXKOxOX
00XNXKXXK0O0Odc::::ccccc:::::::;,,,,,,,,,,;;::::::::::::::::::ccllllllllllllllllllllllllllllllllllllllllllllllooolloooooolodoooooooooooooolooooooooooooolllllooooooooooooolllllllllloONXXKKXKKXNNXKXXNNN
ddxkxddddddddoc::::ccccc::::::;,,,'''''''',,;;::::::::::::::::cccccccllllllllllllllllllllllllllllllllllloooooooooooloooooooddooooddooodddoooooooooooooddollllooooooooooolllllllllllllx000KKkdx0XKXXNXK0O
oooooddddoollc:::::ccccc::::;;;,'''''''''''',,;:::::::::::::::ccccclllllllllllllllllllllllllllllllllllloooooooooooooooooooooooollllllllloollllllllllloooollloooooooooooollllllllllllldxxxddx0KK00XWWNKKX
:;;:ccllc:;;:::::::ccccc:;;;;,,''''''''''''',,,;;::::::::::;;;:ccclllllllllllllllllllllllllllllllllllllooolooollllooooooooooooollllllloolllolllllllllooollooooooooooooooooloolllllllol;,;,,;::cokXX00KXN
:;:ccllcccclxo:;::cccccc;,''''.......''''''''''',,,;;;,;;;;;;,:cccccllllllllllllllllllllllllllllllllllllllooooollllooooooooooolllllllooloooooloolllllllllooooooollooooooooooolllllllll:;:;,,'....;:cldxk
',;;;::,,,;ldo:;::ccccc::;,,'..........''''''''',,;;;;;;;;,;;,;ccccllllllllllllllllllllllllllllllllllllllloolloloololloooooooollooooooooooooolllllllllllloooooooooooooooooooolllllllll;,,,'''......,::cc
            .'::;::cccc:;,,,,'.'''.''''''''','''',;;;,,;,,,'',;cccclllllllllllllllllllllllllllllllloooloooooolooooooooooooooloooooooloooooooollllllllllllloooollooooooooooolllllllllol,..............';c
            .':::::cccc:,',,,,'''''''''',,',,'''',;;;,,,'',''';clcclllllllllllllllllllllllllllllllloooooooooooollloooooloooooooooooooooooooooolooolllloooooooollloooooooooooooololllol,...........'',;:c
          ....;::::cccc:,',;;;;,'''',''',,,,,'''',,;,,,''',''';clllllllllllllllllllllllllllllloollloooooooooooollloooooololoooooooooooooooooolooooooooooooooooollooooooooooooolllllllolcccccclllloodxxdd
.............';::::c::c:,',;:::;''''''...',,''''',,;;;;,,,,,',:cllllllllllllllllllllllllllllllloooooooooooolooooolllllllllllooolllloooooolloooooooooolooooooooooooooooooooooolllllllldkkkkkkkOOOOO000KXN
.............';::::c::c;,,;;:;,,'''''''''',,''''''',,,;;;;;;,;cccccllcclllllllllllllllllllllllllollllllllllllooooolllllllllllolllllllooollloooooooooolllooooooooooooooooooooolllllllldOKKKKKKKKKKKKKXXXX
.............';::::cccc:,;;;,'..,''''''',,;;'','''''''',,;:;;;cccccccccllllllllllllllllllllllllllllllllllllllllooollllllllllloolllloooooooooooooololllloooooooooooooooooooooolllllllld0XKXXXXXXXXXXXXXXK
:::::::::::::;;::::cccc:,,'.....',,''...''''..,,,,,,'''',;::::cccccccccllllllllllllllllllllllllllloooollllllllllllllllllllllllllloooooooooollloolllllloooooooooooooooooooooollllollold0XXXXXXXXXXXXXXXXK
ddddddddoooooc;::::::cc;.........''....''.....',''',,,,',;:::::cccccllllllllllllllllllllllllllllllloollllllllllllllllllllllllloolooooooooloolllollllllloooooooooooooooooooooollllllood0XXXXXXXXXXXXXXXXK
Okkkkkxxxxxxdc;::::::::,.............';;;;,'..''''''''''',;:;;:ccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllooooooooooollllloollloooloooooooooooooooooooooooollllllloOXXXXXXXXXXXXXXXXX
NXKK00OOOkkkxl;::::::c:,...........';::::::,...'....''''.';;,,:ccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllloooooooooollloooooolollloooooooooooooooooooooooollllllloOXXXXXXXXXXXXXXXXX
KKKK000OOkkkxc;::::::c:,............';;:::;,.........''..',,',:cccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllooooooolloooooooooollllloooloooooooooooooooooooooollllloOXXXXXXXXXXXXXXXXX
OOOOkkkkkkkkdc;::::c:c:'.............';:::;'.........''''',,;:cccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllloooooooooooooolloolooooooooooooooooooooooooooooooollllloOXXXXXXXXXXXXXXXXX
OOOOkkkkkkxkdc;::::ccc:'..............';::;...........',;,,;::ccccccccclllllllllllllllllllllllllllllllllllllllllllollllllllloolooooooooollllllooloooooooooooooooooooooooooooooolllllloOXXXXXXXXXXXXXXXXX
OOOkkkkkkkxxdc;::::ccc:'...............';:,...........,::;,:::cccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllollloollllllollllooooooolloooooooooooooooooooooooooollllokXXXXXXXXXXXXXXXXX
OOOkkkkkkkxxd:;::::c:::'................','..........';:;,',::ccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllloooollllllllllllloooolloloooooooooooooloooooooooooooooolokKXXXXXXXXXXXXXXXX
OOkkkkkkkkxxd:;::::::::...............................',''',;:ccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllooollllllllllllloooooooolllooooooooollooooooooooooooooookKXXXXXXXXXXXXXXXX
OOkkkkkkkkxxd:;::::::c;................................''';,,;:cccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllloollllllllooooooooollooooloooooooooooooxKXXXXXXXXXXXXXXXX
Okkkkkkkkkxxo:;:::::::;................................'',;,',:ccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllooooooooooolloollloooooooooooooxKXXXXXXXXXXXXXXXX
Okkkkkkkkkxxo:;::::::c;..............................''',,,,,;:cccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllolllllllllllllllllloooooolloooooolloolloooooooooooooxKXXXXXXXXXXXXXXXX
Okkkkkkkkxxxo:;:::::::;...............................''''''';:ccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllolllllooooooooooooollllolllooooooooooold0XXXXXXXXXXXXXXXX
Okkkkkkkkkxxo:;;::::::;..............................'''''..',:ccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllloooooooooolllloollooollllllllld0XXXXXXXXXXXXXXXX
Okkkkkkkkkxxo:;;::::::,......................................,:cccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllooooooollllllllllllllllllllld0XXXXXXXXXXXXXXXX
Okkkkkkkkxxxo:;;;:::::,......................................':cccccccccccccccccllllllcllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllloooooooollllooooollllllllllllllld0XXXXXXXXXXXXXXXX
kkkkkkkkkxxxl;;;::::::,......................................':ccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllooooooooooooollloloooolllollllllllllloOXXXXXXXXXXXXXXXX
kkkkkkkkkxxxl;;;::::::,......................................':cccccccccccccccccclllllcclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllooooooooolloooloooolllllllllllllloOXXXXXXXXXXXXXXXX
Okkkkkkkkkxxl;;;::::::,......................................':cccccccccccccccccccccclcclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllooolllllloollloolllollllllllllloOXKKKKKXXXXXXXXXX
kkkkkkkkkkkxl;;;::::::'......................................':ccccccccccccccccccccclllccclccllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllloOKKKKKXXXXXXXXXXX
Okkkkkkkkkkxl;;;::::::'......................................':cccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllokKKKKXXXXXXXXXXXX
OOkkkkkkkkkxl;;;::::::'......................................':ccccccccccccccccccccccccccllcclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllokKKKKKXXXXXXXXXXX
OOOkkkkkkkkxl;;;::::::'......................................,:cccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllokKXKKKXXXXXXXXXXX
OOkkkkkkkkkxl;;;:::::;'......................................,:ccccccccccccccccccccccccccccccccclllllllllllllllllllllllllcllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllokKXKKXXXXXXXKKKXX
OOkkkkkkkkkxc;;;:::::;.......................................,::cccccccccccccccccccccccccccccccclllllllllllllllccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllkKKKKXXXXXXXXKKXX
OOOOkkkkkkkxc;;;:::::;.......................................,::::::::cccccccccccccccccccccccccllllllllccllllllcclcccclllllllclllllllllllllllllllllllllllllllllllllllllllllllllllllllllkKKKKXXKXXXKXXXKK
OOOOOkkkkkkxc;;;:::::;.......................................,::::::::cccccccccccccccccccccccccccccccccccccclllccccclccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllkKKKKKXXXXXXXXXXX
OOOOOOOkkkkxc;;;;::::;.......................................,:::::::c::::ccccccccccccccccccccccccccccccccclcccccccllcccllcccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllkKXKKXXXXXXXXXXXX
OOOOOOOOkkkxc;;;:::::;.......................................,:::::::::::::cccccccccccccccccccccccccccccccccccccccllccccllcccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllkKXKXXXXXXXXXXXXX
OOOOOOOOOkOxc;;;:::::;.......................................,::::::::::::::cccccccccccccccccccccccccccccccccccccclccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllxKXXXXXXXXXXXXXXX
OOOOOOOOOOOxc;;;:::::;.......................................,::::::::::::::::ccccccccccccccccccccccccccccccccccccccccccccccccccclcccllllllllllllllllllllllllllllllllllllllllllllllllllxKXKXXXXXXXXXXXXX
OOOOOOOOOOOxc;;;:::::,.......................................,:::::::::::::::ccccccccccccccccccccccccccccccccccccccccccccccccccclllcclllllllllllllllllllllllllllllllllllllllllllllllllld0XKKXXXXXXXXXXXX
0000000OOOOkc;;;;::::,.......................................,:::::::::::::::ccc:cccccccccccccccccccccccccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllld0KKKKKKKKKKKKXXX
00000000000kc;;;;::::,.......................................,:::::::::::::::::::cccccccccccccccccccccccccccccccccccccccccccccccccclllllcllcccllllllllllllllllllllllllllllllllllllllllldO000000000KKKKKK
00000000000kc;;;:::::,......................................';:::::::::::::::::::::ccc:ccccccccccccccccccccccccccccccccccccccccccccccccccccccccllllllllcccllllllllllllllllllllllllllllldO0000000000000KK
KKKKKKKKKKKkc;;;;::;;,......................................';::::::::::::::::c:::::::::ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccllccllllllllllllllllllllllllllldO0000000KKKKKKKK
XXXXXXXXKKXOc;;;;:;;;,......................................';:::::::::::::::::::::::c:::c::::cccccccccccccccccccccccccccccccccccccccccccclccllclllllllllllclllclllcllllllllllllllllllldO0OOOOkkxxxddool
XXXXXXXXXXXOc;;;;:;;;,......................................';:::::::::::::::::::::::::::::::::c::cccccccllccollollolloollolololcclodlcccloolooloollolodddlcllccllllllllllllllllllllllll:;,,''..........
NNNNNNNNNNN0c;;;;::;;,......................................';::::::::::::::::::::::::::::::::::c:ccccccclollolloololloollllllllccloolccccllcllcllcclllllllllllclllllllllllllllllllllllc'...............
WWWWWWWWWWW0c,;;;::;;,......................................';::::::::::::::::::::::::::::::::::c:cccccccccccccccccccccccccccccccccccccccccccccccccccccccclllccllllllllllllllllllllllllc'...............
WWWWWWWNNNW0c,;;;:;;;'......................................';:::::::::::::::::::::::::::::::::::::ccccccccccccccccccccccccccccccccccccccccccccccccccccccllcccccllllllllllllllllllllcllc,...............
NNNNNNNNNNNO:,;;;:;;;'.................,;'...................;::::::::::::::::::::::::::::::::ccccccccccccccccccc::::::::ccccccccccccccccccccccccccccccccllcllllllllllllllcllllllccllllc,...............
XXXNNNNNNNWO:,;;;;;;;'................';;'...................;:;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,''''''''''''''........,:ccccccccccccccccccccccccccclcccllclllllllllllccllllllllllllllc,...............
WWWWWWMMMMM0c,;;;;;;;'................';,.........................''.......................,'..........'.''.............':cccccccccccccccccccccccccccccccllcclllllllllllllllllllllcccccc,...............
MWWWWWWWWNNO:,;;;;;;;'................,;''.'..'..'........''.'....,..'.',.''..'.''.,'.''...'..'.''.''''''''...........'',:ccccccccccccccccccccccccccccccccccccclllllllllllllllccccc::;:l;...............
Okkxxddollc:,,,;;;;;;'................;;,'....'..'.........'.''...'..'.''''''''''''''',,,,,,,,,;;;;;;;;;;;:::::::::::::::ccccccccccccccccccccccccccccccccccccccclllllccllllllcccc:;:cldo;...............
............,,,;;;;;;'...............,;;,'................',,;;;;;;;;;::::::::::::::::::::::::::ccccccccc::::::::::::::::::::cccccccccccccccccccccccccccccccccccccccc:::cc::::::;;;:cc:,................
...........,,,,;;;;;;................;;;;;,...............,;;;::::::::::::::::::::::::::::::::ccccccccc:::::::;;;;;;;;;;,,,,,,,,,,,,,,,,,,'''''''''.....................................................
...........;:::::;;;;...............,;;;;;'...............,;;;;;;;;;;,;;;,,,,,,,,,,,'''''''''''..................................   ..                       .    ......................................
.......''',;:clodooo:'...............'''..........................................                                  ...               .          ..         ......  ....................................
:ccllooddxxkOOO0000k:................ .........                    .                                                              .           .  ..   .        ...    ............................''''''
dxxxxxxkkkOOOOOOOOOl...............................  . ..          .                                 ..      ..     ..                                                ..............''''',,,,;;;;;;;;;;;
xxxddxxxkkOOOO0OOOd,.............................  .... .  ..           .         ..                 ..             ..                                         ................'',,,;;;;;;;;;;;;;;;;;;;;)EOF");
}

#endif // LIVROS_H_INCLUDED
